package main

import (
	"log"
	"log/slog"
	"net/http"
	"os"

	"connectrpc.com/connect"
	"github.com/yoshihiro-shu/tech-blog-admin/backend/interceptor"
	"github.com/yoshihiro-shu/tech-blog-admin/backend/protobuf/gen/backend/v1/backendv1connect" // generated by protoc-gen-connect-go
	"github.com/yoshihiro-shu/tech-blog-admin/backend/service"
	"golang.org/x/net/http2"
	"golang.org/x/net/http2/h2c"
)

func main() {
	logger := slog.New(slog.NewJSONHandler(os.Stdout, nil))
	slog.SetDefault(logger)

	server := &service.BackendServer{}
	interceptors := connect.WithInterceptors(interceptor.Logger())

	mux := http.NewServeMux()
	path, handler := backendv1connect.NewBackendServiceHandler(server, interceptors)
	mux.Handle(path, handler)

	log.Printf("server is started at %s", "localhost:8080")

	http.ListenAndServe(
		":8080",
		// Use h2c so we can serve HTTP/2 without TLS.
		h2c.NewHandler(mux, &http2.Server{}),
	)
}
